### inserir matricula
POST http://localhost:3000/api/v1/matricula
Content-Type: application/json

{
   "id": "gal",
   "aluno": "gal"
}

### Remover matricula
DELETE  http://localhost:3000/api/v1/matricula/dd54d65b-227a-4a82-aa94-696dda5621c4
Content-Type: application/json

### Buscar todas as matriculas
# GET http://localhost:3000/api/v1/matricula

### buscar pelo um id matricula
# GET http://localhost:3000/api/v1/matricula/50963c1f-100e-4e0c-82fc-1ea121b1ab2c

### atualizar o campo matricula
# PUT http://localhost:3000/api/v1/matricula/dd54d65b-227a-4a82-aa94-696dda5621c4
# Content-Type: application/json

# {
#   "aluno": "novoTeste"
# }

########

### inserir
POST http://localhost:3000/api/v1/alunos
Content-Type: application/json

{
  "id": "engesoft",
  "nome": "engesoft",
  "docente": "walter",
  "aluno": "gabriel",
  "disciplina": "tapr"
}

### Remover aluno
DELETE  http://localhost:3000/api/v1/aluno/ae498194-0377-4150-9dc1-04b4046a3672
Content-Type: application/json