openapi: 3.0.1
info:
  title: microservmatricula
  description: My cool TypeScript app
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification
paths:
  /matriculas:
    get:
      summary: Retrieve all matriculas
      responses:
        '200':
          description: Successful operation
          content: {}
    post:
      summary: Create a new matricula
      responses:
        '200':
          description: Successful operation
          content: {}
  /matriculas/{id}:
    get:
      summary: Retrieve a matricula by ID
      responses:
        '200':
          description: Successful operation
          content: {}
    put:
      summary: Update a matricula by ID
      responses:
        '200':
          description: Successful operation
          content: {}
    delete:
      summary: Delete a matricula by ID
      responses:
        '200':
          description: Successful operation
          content: {}
  /examples:
    get:
      tags:
        - Examples
      summary: Retrieve all examples
      responses:
        '200':
          description: Successful operation
          content: {}
    post:
      tags:
        - Examples
      summary: Create a new example
      requestBody:
        description: An example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleBody'
        required: true
      responses:
        '200':
          description: Successful operation
          content: {}
  /examples/{id}:
    get:
      tags:
        - Examples
      summary: Retrieve an example by ID
      parameters:
        - name: id
          in: path
          description: The ID of the example to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content: {}
        '404':
          description: Example not found
          content: {}
  /spec:
    get:
      tags:
        - Specification
      summary: Retrieve the API specification
      responses:
        '200':
          description: Successful operation
          content: {}
components:
  schemas:
    ExampleBody:
      type: object
      title: example
      required:
        - name
      properties:
        name:
          type: string
          example: no_stress
